services:

  portal:
    image: bh2731/viaserra-portal:1.0-26174736
    ports:
      - "8036:80"
    restart: unless-stopped

  manutencao:
    build: ./manutencao
    ports:
      - "7036:80"
    restart: unless-stopped
